-- ============================================================
-- Equipment Borrowing and Return Monitoring System
-- Run this in the Supabase SQL Editor
-- ============================================================

CREATE TABLE equipment (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  equipment_name TEXT NOT NULL,
  category TEXT NOT NULL,
  asset_code TEXT UNIQUE NOT NULL,
  condition TEXT DEFAULT 'Good',
  availability TEXT DEFAULT 'Available',
  created_at TIMESTAMPTZ DEFAULT NOW()
);

CREATE TABLE borrow_transactions (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  equipment_id BIGINT REFERENCES equipment(id),
  borrower_name TEXT NOT NULL,
  borrower_type TEXT NOT NULL,
  department TEXT NOT NULL,
  date_borrowed DATE DEFAULT CURRENT_DATE,
  due_date DATE NOT NULL,
  date_returned DATE,
  status TEXT DEFAULT 'Borrowed',
  user_id UUID REFERENCES auth.users(id),
  created_at TIMESTAMPTZ DEFAULT NOW()
);

-- ============================================================
-- Row Level Security (BR-11: only authenticated users may manage records)
-- ============================================================

ALTER TABLE equipment ENABLE ROW LEVEL SECURITY;
ALTER TABLE borrow_transactions ENABLE ROW LEVEL SECURITY;

-- Equipment: any authenticated user may read/write
CREATE POLICY "Authenticated users can view equipment"
  ON equipment FOR SELECT
  TO authenticated
  USING (true);

CREATE POLICY "Authenticated users can insert equipment"
  ON equipment FOR INSERT
  TO authenticated
  WITH CHECK (true);

CREATE POLICY "Authenticated users can update equipment"
  ON equipment FOR UPDATE
  TO authenticated
  USING (true);

CREATE POLICY "Authenticated users can delete equipment"
  ON equipment FOR DELETE
  TO authenticated
  USING (true);

-- Borrow transactions: any authenticated user may read/write
CREATE POLICY "Authenticated users can view transactions"
  ON borrow_transactions FOR SELECT
  TO authenticated
  USING (true);

CREATE POLICY "Authenticated users can insert transactions"
  ON borrow_transactions FOR INSERT
  TO authenticated
  WITH CHECK (true);

CREATE POLICY "Authenticated users can update transactions"
  ON borrow_transactions FOR UPDATE
  TO authenticated
  USING (true);

-- ============================================================
-- Optional: sample seed data for quick testing
-- ============================================================
-- INSERT INTO equipment (equipment_name, category, asset_code, condition) VALUES
-- ('Epson Projector', 'Projector', 'PROJ-001', 'Good'),
-- ('Acer Laptop', 'Laptop', 'LAP-002', 'Good'),
-- ('Canon Camera', 'Camera', 'CAM-001', 'Fair');
